### ISSUE TITLE
Obtaining code coverage from gcov

### ISSUE THREAD

**Issue by kanghj** [ise-uiuc/FreeFuzz#2]
Hello, congrats on the paper, and thanks for the great work on FreeFuzz, @Anjiang-Wei, @YangChenyuan @dengyinlin! 

What are the steps for using gcov to obtain the c++ code coverage of the tests generated by FreeFuzz? The paper was correct in pointing the importance of the coverage trend analysis, and it would be amazing if the process can be provided in the repository. (:

**Comment by Anjiang-Wei** [comment]
自动回复：您发的邮件已经收到，谢谢。

**Comment by YangChenyuan** [comment]
To get the code coverage of PyTorch, you can use this [tool](https://github.com/pytorch/pytorch/tree/master/tools/code_coverage).
